# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Zjg5NGM3ZjdlZWE4NTBiOTg2OTY2YTA5ZTdhY2E2ZWU3OTYyMjI1MzUwNTkwYjk0YTAxODYyMmRkZjNmMTFmOGVkYjJiOGY3MGNhMzFiZWU1MzExZGFhZjk4MWE4YWE1MzdhMTdkZWY2Y2UyM2MyZjQ4YmQyOWU5NGM2YjBjM2I=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
